/**
 * embed-images.mjs
 * Reads every image from ./pic/, resizes to max 900px and compresses
 * as JPEG (quality 82), then embeds them as base64 data URLs into
 * catalog-print.html, outputting catalog-print-embedded.html —
 * a fully self-contained file that works from disk (no tainted canvas).
 *
 * Run: node embed-images.mjs
 * Requires: node-canvas  (installed in ../node_modules/canvas)
 */

import fs   from 'fs';
import path from 'path';
import { createRequire }    from 'module';
import { fileURLToPath }    from 'url';

const require    = createRequire(import.meta.url);
const { createCanvas, loadImage } = require('../node_modules/canvas');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PIC_DIR   = path.join(__dirname, 'pic');
const SRC_HTML  = path.join(__dirname, 'catalog-print.html');
const OUT_HTML  = path.join(__dirname, 'catalog-print-embedded.html');

const MAX_PX    = 900;   // max width or height in pixels
const QUALITY   = 0.82;  // JPEG quality for compression

// ── 1. Resize + encode every image ───────────────────────────────────────────
const SKIP_EXT = new Set(['.pdf', '.xlsx', '.csv', '.txt', '.js', '.html']);
const imageMap = {};
let totalBefore = 0, totalAfter = 0, count = 0;

const files = fs.readdirSync(PIC_DIR).sort();
for (const f of files) {
  const ext = path.extname(f).toLowerCase();
  if (SKIP_EXT.has(ext)) continue;
  const fullPath = path.join(PIC_DIR, f);
  const rawSize  = fs.statSync(fullPath).size;

  try {
    const img = await loadImage(fullPath);

    // Compute scaled dimensions
    let { width: w, height: h } = img;
    if (w > MAX_PX || h > MAX_PX) {
      const scale = MAX_PX / Math.max(w, h);
      w = Math.round(w * scale);
      h = Math.round(h * scale);
    }

    const canvas = createCanvas(w, h);
    const ctx    = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0, w, h);

    const dataURL = canvas.toDataURL('image/jpeg', QUALITY);
    const outSize = Math.round((dataURL.length - 'data:image/jpeg;base64,'.length) * 3 / 4);

    imageMap[f.toLowerCase()] = dataURL;
    totalBefore += rawSize;
    totalAfter  += outSize;
    count++;

    const pct = Math.round((1 - outSize / rawSize) * 100);
    process.stdout.write(`  ✓ ${f.padEnd(30)} ${Math.round(rawSize/1024)}KB → ${Math.round(outSize/1024)}KB  (−${pct}%)\n`);
  } catch (e) {
    process.stderr.write(`  ✗ SKIP ${f}: ${e.message}\n`);
  }
}

console.log(`\n${count} images: ${Math.round(totalBefore/1024)}KB → ${Math.round(totalAfter/1024)}KB  (saved ${Math.round((1-totalAfter/totalBefore)*100)}%)`);

// ── 2. Read source HTML ───────────────────────────────────────────────────────
let html = fs.readFileSync(SRC_HTML, 'utf8');

// ── 3. Inject image lookup table before first CDN <script> ───────────────────
const injection = `<script>
/* Pre-embedded images — generated by embed-images.mjs
   All are data URLs: canvas NEVER tainted, works from file:// */
window.__IMGS__ = ${JSON.stringify(imageMap)};
</script>
`;

if (html.includes('window.__IMGS__')) {
  // Replace existing injected block
  html = html.replace(/<script>\s*\/\* Pre-embedded[\s\S]*?window\.__IMGS__[\s\S]*?<\/script>\s*\n/, injection);
} else {
  html = html.replace(
    '<script src="https://cdn.jsdelivr',
    injection + '<script src="https://cdn.jsdelivr'
  );
}

// ── 4. Patch ip() to use embedded images ─────────────────────────────────────
// Replace the original one-liner with the lookup version
if (!html.includes('window.__IMGS__[k]')) {
  html = html.replace(
    "function ip(f) { return 'pic/' + f.replace(/ /g, '%20'); }",
    [
      "function ip(f) {",
      "  const k = f.toLowerCase();",
      "  return (window.__IMGS__ && window.__IMGS__[k])",
      "      || ('pic/' + f.replace(/ /g, '%20'));",
      "}",
    ].join('\n')
  );
}

// ── 5. Write output ───────────────────────────────────────────────────────────
fs.writeFileSync(OUT_HTML, html, 'utf8');
const outKB = fs.statSync(OUT_HTML).size / 1024;
console.log(`\n✅  Written: ${path.basename(OUT_HTML)}`);
console.log(`    File size: ${Math.round(outKB)}KB  (${(outKB/1024).toFixed(1)} MB)`);
console.log('\nOpen catalog-print-embedded.html in Chrome and click "צור PDF".');
